### ISSUE TITLE
Shutdown exceptions

### ISSUE THREAD

**Issue by briantopping** [ANierbeck/Karaf-Cassandra#16]
Not sure what's going on here, thought I would make a note of it. I'm very curious to the solution if it was easy to resolve.

When shutting down, I've started getting a long list of exceptions due to Cassandra losing dependencies:

```
Karaf-Cassandra-Embedded[org.apache.cassandra.service.CassandraDaemon] : Exception in thread Thread[nioEventLoopGroup-2-5,10,Configuration Admin Service]
Karaf-Cassandra-Embedded[org.apache.cassandra.service.CassandraDaemon] : Exception in thread Thread[nioEventLoopGroup-2-1,10,Configuration Admin Service]
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:150)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: Unable to load class 'io.netty.util.concurrent.DefaultPromise$2' because the bundle wiring for io.netty.common is no longer valid.
    at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1539)
    at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79)
    at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2018)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 5 more
Karaf-Cassandra-Embedded[org.apache.cassandra.service.CassandraDaemon] : Exception in thread Thread[nioEventLoopGroup-2-2,10,Configuration Admin Service]
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:150)
Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "nioEventLoopGroup-2-5"

    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "nioEventLoopGroup-2-1"
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:150)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "nioEventLoopGroup-2-2"
Karaf-Cassandra-Embedded[org.apache.cassandra.service.CassandraDaemon] : Exception in thread Thread[nioEventLoopGroup-2-4,10,Configuration Admin Service]
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:150)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "nioEventLoopGroup-2-4"
Karaf-Cassandra-Embedded[org.apache.cassandra.service.CassandraDaemon] : Exception in thread Thread[nioEventLoopGroup-2-3,10,Configuration Admin Service]
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:150)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "nioEventLoopGroup-2-3"
Karaf-Cassandra-Embedded[org.apache.cassandra.service.CassandraDaemon] : Exception in thread Thread[nioEventLoopGroup-2-13,10,Configuration Admin Service]
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:150)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "nioEventLoopGroup-2-13"
Karaf-Cassandra-Embedded[org.apache.cassandra.service.CassandraDaemon] : Exception in thread Thread[nioEventLoopGroup-2-7,10,Configuration Admin Service]
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:150)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "nioEventLoopGroup-2-7"
Karaf-Cassandra-Embedded[org.apache.cassandra.service.CassandraDaemon] : Exception in thread Thread[nioEventLoopGroup-2-11,10,Configuration Admin Service]
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:150)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "nioEventLoopGroup-2-11"
Karaf-Cassandra-Embedded[org.apache.cassandra.service.CassandraDaemon] : Exception in thread Thread[nioEventLoopGroup-2-8,10,Configuration Admin Service]
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:150)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "nioEventLoopGroup-2-8"
Karaf-Cassandra-Embedded[org.apache.cassandra.service.CassandraDaemon] : Exception in thread Thread[nioEventLoopGroup-2-15,10,Configuration Admin Service]
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:150)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "nioEventLoopGroup-2-15"
Karaf-Cassandra-Embedded[org.apache.cassandra.service.CassandraDaemon] : Exception in thread Thread[nioEventLoopGroup-2-9,10,Configuration Admin Service]
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:150)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "nioEventLoopGroup-2-9"
Karaf-Cassandra-Embedded[org.apache.cassandra.service.CassandraDaemon] : Exception in thread Thread[nioEventLoopGroup-2-16,10,Configuration Admin Service]
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:150)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "nioEventLoopGroup-2-16"
Karaf-Cassandra-Embedded[org.apache.cassandra.service.CassandraDaemon] : Exception in thread Thread[nioEventLoopGroup-2-6,10,Configuration Admin Service]
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:150)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "nioEventLoopGroup-2-6"
Karaf-Cassandra-Embedded[org.apache.cassandra.service.CassandraDaemon] : Exception in thread Thread[nioEventLoopGroup-2-14,10,Configuration Admin Service]
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:150)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "nioEventLoopGroup-2-14"
Karaf-Cassandra-Embedded[org.apache.cassandra.service.CassandraDaemon] : Exception in thread Thread[nioEventLoopGroup-2-12,10,Configuration Admin Service]
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:150)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "nioEventLoopGroup-2-12"
Karaf-Cassandra-Embedded[org.apache.cassandra.service.CassandraDaemon] : Exception in thread Thread[nioEventLoopGroup-2-10,10,Configuration Admin Service]
java.lang.NoClassDefFoundError: io/netty/util/concurrent/DefaultPromise$2
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
    at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:150)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "nioEventLoopGroup-2-10"
Karaf-Cassandra-Embedded[org.apache.cassandra.service.CassandraDaemon] : Exception in thread Thread[StorageServiceShutdownHook,5,Configuration Admin Service]
java.lang.NoClassDefFoundError: org/apache/cassandra/db/commitlog/CompressedSegment$1
    at org.apache.cassandra.db.commitlog.CommitLogSegmentManager.awaitTermination(CommitLogSegmentManager.java:555)
    at org.apache.cassandra.db.commitlog.CommitLog.shutdownBlocking(CommitLog.java:410)
    at org.apache.cassandra.service.StorageService$1.runMayThrow(StorageService.java:674)
    at org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: Unable to load class 'org.apache.cassandra.db.commitlog.CompressedSegment$1' because the bundle wiring for Karaf-Cassandra-Embedded is no longer valid.
    at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1539)
    at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79)
    at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2018)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 5 more

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "StorageServiceShutdownHook"
```

This is with a virgin Karaf 4.0.3, Java 1.8.0_51, Karaf-Cassandra 1.0.1. There doesn't seem to be anything particularly unique about the `feature.xml` that I am using:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<features xmlns="http://karaf.apache.org/xmlns/features/v1.3.0" name="net.mauswerks.trading.journal">
    <repository>mvn:de.nierbeck.cassandra/Karaf-Cassandra-Feature/1.0.1/xml/features</repository>
    <feature name="net.mauswerks.trading.journal" description="net.mauswerks.trading.journal" version="0.1.0.SNAPSHOT">
        <config name="de.nierbeck.cassandra.embedded" append="false">
            cassandra.yaml = ${karaf.base}/etc/net.mauswerks.trading.journal.cassandra.yaml
        </config>
        <configfile finalname="etc/net.mauswerks.trading.journal.cassandra.yaml">mvn:net.mauswerks.trading/net.mauswerks.trading.journal/0.1-SNAPSHOT/yaml/config</configfile>
        <feature version="1.0.1" prerequisite="false" dependency="false">Karaf-Cassandra-Embedded</feature>
    </feature>
</features>
```

The Cassandra config only has changes to ports. 

Is this something that's resolvable with something like https://karaf.apache.org/manual/latest/users-guide/provisioning.html#Dependency ?

No worries if this is a diversion... Happy new year! :)

**Comment by ANierbeck** [comment]
AFAIK the demon does take some time to shut-down, therefore it very well might be that all other bundles are already stopped.

**Comment by briantopping** [comment]
Yes I figured as much. It must have emerged as I added one or more dependencies on a Cassandra bundle from the app I am working on. Just didn't know if you had seen this before. I'll dig more, cheers!
